question_data = [{"question":"What makes a qubit different to a classical bit?", "correct_answer":"superposition", 
                  "incorrect_answers":["energy","hardware","computational speed"]}, 
                 {"question":"Which pair of gates are applied to entangle two qubits?", "correct_answer":"H & CX", 
                  "incorrect_answers":["X & CX", "CX & H", "H & CZ"]}, 
                 {"question":"What speed-up does Grover's Algorithm promise over classical unstructured search?", "correct_answer":"quadratic", 
                  "incorrect_answers":["cubic", "exponential", "depends on the problem"]}, 
                 {"question":"How many classical and quantum mechanical queries respectively does the Deutsch-Josza Algorithm take to determine the constancy (or otherwise) of a function?", "correct_answer":"2^(n-1)+1 and 1", 
                  "incorrect_answers":["2^n and n", "n^2 and logn", "n and 1"]}, 
                 {"question":"What does the Shor's Algorithm incoporate in its circuit construction?", "correct_answer":"Quantum Fourier Transform", 
                  "incorrect_answers":["Quantum Teleportation", "Entanglement Swapping", "Quantum Tunneling"]}]